all: \
	insert_bnode.o \
	tree_depth.o \
	traversals.o \
	locate_parent.o \
	locate_sibling.o \
	tree_trace.o \
	locate_root.o

insert_bnode.o: insert_bnode.c
	gcc -c insert_bnode.c

tree_depth.o: tree_depth.c
	gcc -c tree_depth.c

traversals.o: traversals.c
	gcc -c traversals.c

locate_parent.o: locate_parent.c
	gcc -c locate_parent.c

locate_sibling.o: locate_sibling.c
	gcc -c locate_sibling.c

tree_trace.o: tree_trace.c
	gcc -c tree_trace.c
