all: \
	balance_tree.o \
	identify_family.o \
	rotation_cases.o \
	rotations.o

balance_tree.o: balance_tree.c
	gcc -c balance_tree.c

identify_family.o: identify_family.c
	gcc -c identify_family.c

rotation_cases.o: rotation_cases.c
	gcc -c rotation_cases.c

rotations.o: rotations.c
	gcc -c rotations.c
